### ISSUE TITLE
Upgrade cats-effect to 1.0.0

### ISSUE THREAD

**Issue by dbousamra** [Verizon/knobs#63]
Now that cats-effect 1.0 is out it'd be nice if this used it. I am receiving errors like this:

```
Exception in thread "main" java.lang.NoSuchMethodError: cats.effect.Async.shift(Lscala/concurrent/ExecutionContext;)Ljava/lang/Object;
	at knobs.Resource$.watchStream(Resource.scala:155)
	at knobs.Resource$.$anonfun$watchEvent$4(Resource.scala:222)
	at knobs.Resource$.$anonfun$watchEvent$4$adapted(Resource.scala:221)
	at cats.effect.IO$Map.apply(IO.scala:1407)
	at cats.effect.IO$Map.apply(IO.scala:1403)
	at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:216)
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:216)
	at cats.effect.IO.unsafeRunTimed(IO.scala:321)
	at cats.effect.IO.unsafeRunSync(IO.scala:240)
```

I assume this is because the cats-effect version is a bit older?

**Comment by rossabaker** [comment]
Correct. #61 starts down this road.

I have a presentation to prepare, and probably can't look at this until next week, but I imagine getting on fs2-1.0.0-M5 and cats-effect-1.0.0 might not be too hard starting from #61.

**Comment by dbousamra** [comment]
Okay. I might start with that branch and sent a larger PR with both FS2 and Cats effect upgraded.
